#build:
#  script:
#    - echo "Hello World"
#
#
#my_first_job:
#    image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
#    script:
#        - python -c 'import this'
#        - echo "My first CI produced file" > output.txt
#        - ls
#        - ls /
#        - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
#        - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
#        - source setup_here.sh
#        - source buildthis.sh
#

before_script:
  - yum install -y ssh-client
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -e "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa


job_cvmfs:
  tags:
    # Make you job be executed in a shared runner that has CVMFS mounted
    - cvmfs
  
  variables:
    # example base path for an Experiment environment
    ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  
  script:
    # access CVMFS
    - ls /cvmfs/atlas.cern.ch/
    
    # It is possible to load an Experiment environment from CVMFS as follows:
    
    # First, install any package required by the specific experiment script
    # (exact list to be seen with maintainers of the experiment environment)
    - yum install -y man 
    # GitLab-CI sets the errexit option (set -e) so the build stops when a
    # command fails, but environment setup scripts typically expect errexit off.
    # Temporarily disable errexit when sourcing the setup script.
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e



job_build:
    #image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    tags:
      # Make you job be executed in a shared runner that has CVMFS mounted
      - cvmfs
    variables:
      # example base path for an Experiment environment
      ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
      #GIT_SUBMODULE_STRATEGY: recursive 
    script:
      #- mkdir -p ~/.ssh
          #- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          #- echo -e "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa
          #- chmod 600 ~/.ssh/id_rsa
        - yum install -y man 
        - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
        - set +e && source setup_here.sh; set -e
        - set +e && source setup_module.sh; set -e
        - source setup_module.sh --head
        - source buildthis.sh


    #job_gaugi_atlas:
    #    #image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    #    tags:
    #      # Make you job be executed in a shared runner that has CVMFS mounted
    #      - cvmfs
    #    variables:
    #      # example base path for an Experiment environment
    #      ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    # 
    #    script:
    #        - yum install -y man 
    #        - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
    #        - set +e && source setup_here.sh; set -e
    #        - source buildthis.sh
    #        - cd build/
    #        - ls *
    #        #- source build/x86_64-slc6-gcc62-opt/setup.sh
    #        #- source Validation/test/test_gaugi_atlas.sh






