#build:
#  script:
#    - echo "Hello World"
#
#
#my_first_job:
#    image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
#    script:
#        - python -c 'import this'
#        - echo "My first CI produced file" > output.txt
#        - ls
#        - ls /
#        - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
#        - source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh
#        - source setup_here.sh
#        - source buildthis.sh
#

job_cvmfs:
  tags:
    # Make you job be executed in a shared runner that has CVMFS mounted
    - cvmfs
  
  variables:
    # example base path for an Experiment environment
    ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  
  script:
    # access CVMFS
    - ls /cvmfs/atlas.cern.ch/
    
    # It is possible to load an Experiment environment from CVMFS as follows:
    
    # First, install any package required by the specific experiment script
    # (exact list to be seen with maintainers of the experiment environment)
    - yum install -y man 
    # GitLab-CI sets the errexit option (set -e) so the build stops when a
    # command fails, but environment setup scripts typically expect errexit off.
    # Temporarily disable errexit when sourcing the setup script.
    - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e



job_build:
    #image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    tags:
      # Make you job be executed in a shared runner that has CVMFS mounted
      - cvmfs
    variables:
      # example base path for an Experiment environment
      ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
 
    script:
        - yum install -y man 
        - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
        - set +e && source setup_here.sh; set -e
        - source buildthis.sh


job_gaugi_atlas:
    #image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
    tags:
      # Make you job be executed in a shared runner that has CVMFS mounted
      - cvmfs
    variables:
      # example base path for an Experiment environment
      ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
 
    script:
        - yum install -y man 
        - set +e && source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh; set -e
        - set +e && source setup_here.sh; set -e
        - source buildthis.sh
        - source build/x86_64-slc6-gcc62-opt/setup.sh
        - source Validation/test/test_gaugi_atlas.sh






